### ISSUE TITLE
uint64 not supported in set

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#109]
We can not set uint64 values 

```jsons
11:15:02 [WARN] Error processing request for Vehicle.Private.Systemstats.Uptime: {
    "action": "set", 
    "error": {
        "message": "The type uint64 is not supported ", 
        "number": 401, 
        "reason": "Unknown error"
    }, 
    "requestId": "1971465630", 
    "timestamp": 1612610102206
} 
```

when specified in vspec as

```yaml
- Vehicle.Private.Systemstats.Uptime:
  type: sensor
  datatype: uint64
  description: "Uptime of the system"
```

Probably problem here https://github.com/eclipse/kuksa.val/blob/12e9f289f8ec39871f9c4bcaaf3f7bf231153474/src/VssDatabase.cpp#L68
