### ISSUE TITLE
Databroker Git version information in container seems to be incorrect

### ISSUE THREAD

**Issue by SebastianSchildt** [eclipse/kuksa.val#516]
This came up in review of #506 

Solution are not elegant, but easy

In git checkout action no tags are available, and can neither be checked, options are
 - no shallow clone, do a full clone: Easy, but the larger the repo gets the more overhead
 - wait for this to be fixed: https://github.com/actions/checkout/pull/579 (seems unrealistic GH ignored it for a long time)
 - fetch some amount of history, including the last tag (that worked in the past)

**Comment by SebastianSchildt** [comment]
Maybe we should think about it in terms of Github Releases: Those should be automated via GH actions, and there we shoudl decide the "correct" way to determine version information

**Comment by erikbosch** [comment]
As a comment. For kuksa-python-sdk we do not do a shallow clone in CI. Is the size actually a problem?

```
    - uses: actions/checkout@v4
      with:
        # Fetch everything to get tags working as expected
        fetch-depth: 0
        submodules: 'true'
```
